version: '3.8'

services:
  nasa-rover-app:
    build: .
    container_name: nasa-rover-app
    environment:
      - NASA_API_KEY=DEMO_KEY # Replace with your actual NASA API key
    volumes:
      - ./nasa_images:/app/nasa_images # Mount the images directory to persist downloaded images
      # Uncomment if you want to override the dates file
      # - ./custom_dates.txt:/app/src/main/resources/dates.txt